Add unit tests for how the rows in the TwoFAVC are computed
wordpress-mobile/WordPressAuthenticator-iOS pull request #810
Opened 2023-11-29 01:20 UTC by mokagio

Builds on top #809 . While looking at that PR, I noticed that there are 3 essentially boolean parameters that drive the rows behavior (either actual `Bool` or `Optional` `.some` vs `.none`). That results into eight _possible_ runtime input configurations. Too many to test manually, but easily testable via unit tests.

---

- [x] I have considered if this change warrants release notes and have added them to the appropriate section in the `CHANGELOG.md` if necessary. — N.A.

2023-11-29 01:26 UTC, mokagio commented on WordPressAuthenticatorTests/TwoFAViewControllerTests.swift
> +}
Note for the future. `nonceWebauthn` and `passkeysEnabled` are always tied together, so we could simplify this code by adding a middle layer.

Something like

```swift
enum ShouldUsePasskeys {
  case false
  case true(nonce: String)
}
```

We would then have tests for

- Computing a `ShouldUsePasskeys` given `nonceWebauthn` and `passkeysEnabled` (four possibilties)
- Computing rows given `String?` error messages and `ShouldUsePasskeys` (four possibilities)

The number of possibilities would be the same as now, but each step would be individually easier to understand

2023-11-29 01:27 UTC, mokagio commented on WordPressAuthenticatorTests/TwoFAViewControllerTests.swift
> +}
I acknowledge that `ShouldUsePasskeys` looks a lot like `Optional`, but I find it's clearer in expressing its meaning.

2023-11-29 05:12 UTC, jkmassel requested changes

2023-11-29 05:12 UTC, jkmassel commented on WordPressAuthenticatorTests/TwoFAViewControllerTests.swift
> +        let defualtRows: [TwoFAViewController.Row] = [.instructions, .code, .alternateInstructions, .sendCode]
```suggestion
        let defaultRows: [TwoFAViewController.Row] = [.instructions, .code, .alternateInstructions, .sendCode]
```

etc, below

2023-11-29 23:49 UTC, mokagio commented on WordPressAuthenticatorTests/TwoFAViewControllerTests.swift
> +            defualtRows
```suggestion
            defaultRows
```

2023-11-29 23:50 UTC, mokagio commented on WordPressAuthenticatorTests/TwoFAViewControllerTests.swift
> +            defualtRows
```suggestion
            defaultRows
```

2023-11-29 23:50 UTC, mokagio commented on WordPressAuthenticatorTests/TwoFAViewControllerTests.swift
> +            defualtRows
```suggestion
            defaultRows
```

2023-11-30 04:45 UTC, jkmassel approved these changes
Thanks for indulging my silly typo fix!

2023-11-30 20:54 UTC, mokagio commented
> Thanks for indulging my silly typo fix!

Not at all silly! As you know, _tpyos_ matter here. Ref pb6Nl-dHI-p2

2023-11-30 20:55 UTC, merged